CREATE TABLE pets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    price INTEGER NOT NULL
);

CREATE TABLE sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pet_id INTEGER NOT NULL,
    price INTEGER NOT NULL,
    date DATE NOT NULL,
    FOREIGN KEY (pet_id) REFERENCES pets(id)
);